name = input("Enter your name:")
department = input("Enter your department:")
score_english = int(input("Enter score English:"))
score_maths = int(input("Enter score Maths:"))
score_economic = int(input("Enter score Economic:"))
score_physics = int(input("Enter score Physics:"))

print(f"Name        :  {name}")
print(f"Department  :  {department}\n")
print("Here are your course scores:\n" )
print(f"English     :    {score_english}")
print(f"Maths       :    {score_maths}")
print(f"Economic    :    {score_economic}")
print(f"Physics      :    {score_physics}")
print("\nThank you for using this program!\n")